### ISSUE TITLE
Interpreting results files

### ISSUE THREAD

**Issue by sachit-menon** [noahshinn024/reflexion-human-eval#3]
Hi, super interesting work here! I was wondering how to interpret the results files in `root` -- initially I thought `is_solved` meant correct or not, and that would indeed give 87.8% for Reflexion with GPT-4; but then the equivalent file without Reflexion gets 81.7 when my impression is that should be 67. How should I be interpreting the columns, and if is_solved != correct, how do I check correctness? + I see the reflections for the ones that have `is_solved` False, but not the predicted (incorrect) solutions, how can I see those?

**Comment by drammen94** [comment]
@sachit-menon i know this is unrelated to your question, but did you change any specific parameters when running the solution? i get is_solved= False on all the tasks

**Comment by sachit-menon** [comment]
I haven't even tried running it yet, just looking at the already-included output files 😅

**Comment by drammen94** [comment]
Looks like the code doesnt log the corret solutions

From reflixion.py:

        if is_solved:
            item["is_solved"] = True
        else:
            item["is_solved"] = False
            item["solution"] = ""
        item["reflections"] = reflections
        write_jsonl(log_path, [item], append=True)

**Comment by noahshinn024** [comment]
> Hi, super interesting work here! I was wondering how to interpret the results files in `root` -- initially I thought `is_solved` meant correct or not, and that would indeed give 87.8% for Reflexion with GPT-4; but then the equivalent file without Reflexion gets 81.7 when my impression is that should be 67. How should I be interpreting the columns, and if is_solved != correct, how do I check correctness? + I see the reflections for the ones that have `is_solved` False, but not the predicted (incorrect) solutions, how can I see those?

Hi, thanks for the note! I've pushed some changes with cleanup on some of the logic and with another rerun of the GPT-4 results for those that do not want to rerun the entire benchmark. Use `./validate_py_results.py` as a util script for new results if you choose to rerun.

**Comment by noahshinn024** [comment]
> Looks like the code doesn't log the correct solutions
> 
> From reflexion.py:
> 
> ```
>     if is_solved:
>         item["is_solved"] = True
>     else:
>         item["is_solved"] = False
>         item["solution"] = ""
>     item["reflections"] = reflections
>     write_jsonl(log_path, [item], append=True)
> ```

Thanks for the note. I've cleaned up the code a bit to remove redundancy. Previously, I was only logging successful solutions.
